export const BRAND_DATA = 'BRAND_DATA'

export const CATEGORY_DATA = 'CATEGORY_DATA'

export const MODEL_DATA = 'MODEL_DATA'

export const SPEC_DATA = 'SPEC_DATA'

export const PRODUCT_SPU_DATA = 'PRODUCT_SPU_DATA'

export const PRODUCT_SKU_DATA = 'PRODUCT_SKU_DATA'

export const PRODUCT_UNIQUE = 'PRODUCT_UNIQUE'

export const PRODUCT_SPU_INFO = 'PRODUCT_SPU_INFO'
export const PRODUCT_SKU_INFO = 'PRODUCT_SKU_INFO'

export const OPTION_ID = 'OPTION_ID'

export const OPTION_VALUE_DATA = 'OPTION_VALUE_DATA'

export const PRODUCT_SPU_AUDIT_DATA = 'PRODUCT_SPU_AUDIT_DATA'

export const PRODUCT_SKU_AUDIT_DATA = 'PRODUCT_SKU_AUDIT_DATA'
