export const PROJECT_DATA = 'PROJECT_DATA'

export const PROJECT_DETAIL = 'PROJECT_DETAIL'

export const PROJECT_LOAN = 'PROJECT_LOAN'

export const CRM_DEPLIST = 'CRM_DEPLIST'
export const PROJECT_RECORD = 'PROJECT_RECORD'

export const PROJECT_PUNCH = 'PROJECT_PUNCH'

export const TABPRELIMINARYREVIEW = 'TABPRELIMINARYREVIEW'
export const INFORMATION_DETAIL = 'INFORMATION_DETAIL'
export const LIST_DETAIL = 'LIST_DETAIL'
export const INFORMATION_EDIT_DETAIL = 'INFORMATION_EDIT_DETAIL'

export const REFUSE_INFO = 'REFUSE_INFO'
