export const PROJECT_DATA = 'PROJECT_DATA'

export const PROJECT_DETAIL = 'PROJECT_DETAIL'

export const PROJECT_LOAN = 'PROJECT_LOAN'

export const PROJECT_RECORD = 'PROJECT_RECORD'

export const PROJECT_PUNCH = 'PROJECT_PUNCH'
