export const ACTIVITY_AREA_DATA = 'ACTIVITY_AREA_DATA'

export const ACTIVITY_SKU_DATA = 'ACTIVITY_SKU_DATA'

export const SECKILL_DATA = 'SECKILL_DATA'

export const SET_SECKILL_SALE_AREA_LIST = 'SET_SECKILL_SALE_AREA_LIST'

export const SET_SELECT_SECKILL_PRODUCT = 'SET_SELECT_SECKILL_PRODUCT'

export const SECKILL_SKU_DATA = 'SECKILL_SKU_DATA'

export const SELECT_SKU_DATA = 'SELECT_SKU_DATA'

export const LIST_TRACK = 'LIST_TRACK'
