export const CLOUD_ACTDETAIL = 'CLOUD_ACTDETAIL'

export const CLOUD_ACTLIST = 'CLOUD_ACTLIST'

export const CLOUD_ALARM_LIST = 'CLOUD_ALARM_LIST' // 告警列表
export const CLOUD_ALARM_PAGINATION = 'CLOUD_ALARM_PAGINATION' // 告警列表分页
export const CLOUD_EQUIPMENT_ERROR_LIST = 'CLOUD_EQUIPMENT_ERROR_LIST' // 设备故障列表
export const CLOUD_EQUIPMENT_ERROR_PAGINATION = 'CLOUD_EQUIPMENT_ERROR_PAGINATION' // 设备故障列表分页
export const CLOUD_DICT = 'CLOUD_EQUIPMENT_ERROR_DICT' // 设备故障字典

export const CLOUD_SMART_PLAY_LIST = 'CLOUD_SMART_PLAY_LIST' // 智能玩法列表
export const CLOUD_SMART_PLAY_PAGINATION = 'CLOUD_SMART_PLAY_PAGINATION' // 智能玩法列表分页
export const CLOUD_SMART_PLAY_POST_DETAIL = 'CLOUD_SMART_PLAY_POST_DETAIL' // 智能玩法文章详情

export const CLOUD_SEND_MESSAGE_LIST = 'CLOUD_SEND_MESSAGE_LIST' // 智能玩法列表
export const CLOUD_SEND_MESSAGE_PAGINATION = 'CLOUD_SEND_MESSAGE_PAGINATION' // 智能玩法列表分页
export const CLOUD_SEND_MESSAGE_POST_DETAIL = 'CLOUD_SEND_MESSAGE_POST_DETAIL' // 智能玩法文章详情

// 设备折线图
export const CLOUD_HISTORY_REPORT = 'CLOUD_HISTORY_REPORT' // 智能设备折线
export const CLOUD_RUNTIME_REPORT = 'CLOUD_RUNTIME_REPORT' // 智能时间折线

export const CLOUD_DEVICE_COUNT = 'CLOUD_DEVICE_COUNT' // 设备总数
export const CLOUD_DEVICE_DETAIL_LIST = 'CLOUD_DEVICE_DETAIL_LIST' // 设备详情列表
export const CLOUD_DEVICE_DETAIL_PAGINATION = 'CLOUD_DEVICE_DETAIL_PAGINATION' // 设备详情分页

export const CLOUD_HOME_DETAIL_LIST = 'CLOUD_HOME_DETAIL_LIST' // 家庭详情分页
export const CLOUD_HOME_DETAIL_PAGINATION = 'CLOUD_HOME_DETAIL_PAGINATION' // 家庭详情分页
export const CLOUD_HOME_OP_DETAIL_LIST = 'CLOUD_HOME_OP_DETAIL_LIST' // 中央空调物联
export const CLOUD_HOME_OP_DETAIL_PAGINATION = 'CLOUD_HOME_OP_DETAIL_PAGINATION' // 中央空调物联
export const CLOUD_HOME_CO_DETAIL_LIST = 'CLOUD_HOME_CO_DETAIL_LIST' // 家庭详情分页
export const CLOUD_HOME_CO_DETAIL_PAGINATION = 'CLOUD_HOME_CO_DETAIL_PAGINATION' // 家庭详情分页
export const CLOUD_HOME_AP_DETAIL_LIST = 'CLOUD_HOME_AP_DETAIL_LIST' // 家庭详情分页
export const CLOUD_HOME_AP_DETAIL_PAGINATION = 'CLOUD_HOME_AP_DETAIL_PAGINATION' // 家庭详情分页
export const CLOUD_HOME_RT_DETAIL_LIST = 'CLOUD_HOME_RT_DETAIL_LIST' // 家庭详情分页
export const CLOUD_HOME_RT_DETAIL_PAGINATION = 'CLOUD_HOME_RT_DETAIL_PAGINATION' // 家庭详情分页
export const CLOUD_HOME_DETAIL_SEARCH_DICT = 'CLOUD_HOME_DETAIL_SEARCH_DICT' // 家庭详情搜索字典

export const CLOUD_HOME_COMFORT_SCENE = 'CLOUD_HOME_COMFORT_SCENE' // 舒适度场景
export const CLOUD_HOME_COMFORT_SCENE_PAGINATION = 'CLOUD_HOME_COMFORT_SCENE_PAGINATION' // 舒适度场景分页页码
export const CLOUD_HOME_COMFORT_SCENE_STATISTICS = 'CLOUD_HOME_COMFORT_SCENE_STATISTICS' // 舒适度场景统计报表
export const CLOUD_ALARM_CHART = 'CLOUD_ALARM_CHART'
export const CLOUD_SEND_MESSAGE_DETAIL_CHART = 'CLOUD_SEND_MESSAGE_DETAIL_CHART' // 消息推送效果详情
export const CLOUD_USER_FEEDBACK_LIST = 'CLOUD_USER_FEEDBACK_LIST' // 用户反馈列表
export const CLOUD_USER_FEEDBACK_PAGINATION = 'CLOUD_USER_FEEDBACK_PAGINATION' // 用户反馈列表分页
export const CLOUD_COMFORT_ENCYCLOPEDIA_LIST = 'CLOUD_COMFORT_ENCYCLOPEDIA_LIST' // 舒适小百科列表
export const CLOUD_COMFORT_ENCYCLOPEDIA_LIST_PAGINATION = 'CLOUD_COMFORT_ENCYCLOPEDIA_LIST_PAGINATION' // 舒适小百科分页页码
export const CLOUD_COMFORT_ENCYCLOPEDIA_DETAIL = 'CLOUD_COMFORT_ENCYCLOPEDIA_DETAIL' // 舒适小百科详情
