export const CLOUD_ACTDETAIL = 'CLOUD_ACTDETAIL'

export const CLOUD_ACTLIST = 'CLOUD_ACTLIST'

export const CLOUD_ALARM_LIST = 'CLOUD_ALARM_LIST' // 告警列表
export const CLOUD_ALARM_PAGINATION = 'CLOUD_ALARM_PAGINATION' // 告警列表分页
export const CLOUD_EQUIPMENT_ERROR_LIST = 'CLOUD_EQUIPMENT_ERROR_LIST' // 设备故障列表
export const CLOUD_EQUIPMENT_ERROR_PAGINATION = 'CLOUD_EQUIPMENT_ERROR_PAGINATION' // 设备故障列表分页
export const CLOUD_EQUIPMENT_ERROR_DICT = 'CLOUD_EQUIPMENT_ERROR_DICT' // 设备故障字典

export const CLOUD_SMART_PLAY_LIST = 'CLOUD_SMART_PLAY_LIST' // 智能玩法列表
export const CLOUD_SMART_PLAY_PAGINATION = 'CLOUD_SMART_PLAY_PAGINATION' // 智能玩法列表分页
export const CLOUD_SMART_PLAY_POST_DETAIL = 'CLOUD_SMART_PLAY_POST_DETAIL' // 智能玩法文章详情

// 设备折线图
export const CLOUD_HISTORY_REPORT = 'CLOUD_HISTORY_REPORT' // 智能设备折线
export const CLOUD_RUNTIME_REPORT = 'CLOUD_RUNTIME_REPORT' // 智能时间折线