export const CLOUD_ACTDETAIL = 'CLOUD_ACTDETAIL'

export const CLOUD_ACTLIST = 'CLOUD_ACTLIST'

export const CLOUD_ALARM_LIST = 'CLOUD_ALARM_LIST' // 告警列表
export const CLOUD_ALARM_PAGINATION = 'CLOUD_ALARM_PAGINATION' // 告警列表分页
export const CLOUD_EQUIPMENT_ERROR_LIST = 'CLOUD_EQUIPMENT_ERROR_LIST' // 设备故障列表
export const CLOUD_DEVICE_ID_IMPORT = 'CLOUD_DEVICE_ID_IMPORT' // 设备故障列表
export const CLOUD_EQUIPMENT_ERROR_PAGINATION = 'CLOUD_EQUIPMENT_ERROR_PAGINATION' // 设备故障列表分页
export const CLOUD_DEVICE_ID_IMPORT_PAGINATION = 'CLOUD_DEVICE_ID_IMPORT_PAGINATION' //
export const CLOUD_DICT = 'CLOUD_EQUIPMENT_ERROR_DICT' // 设备故障字典
export const CLOUD_IMPORT_DICT = 'CLOUD_IMPORT_DICT' //

export const CLOUD_SMART_PLAY_LIST = 'CLOUD_SMART_PLAY_LIST' // 智能玩法列表
export const CLOUD_SMART_PLAY_PAGINATION = 'CLOUD_SMART_PLAY_PAGINATION' // 智能玩法列表分页
export const CLOUD_DEVICE_BRAND_NO = 'CLOUD_DEVICE_BRAND_NO'
export const CLOUD_SMART_PLAY_POST_DETAIL = 'CLOUD_SMART_PLAY_POST_DETAIL' // 智能玩法文章详情

export const CLOUD_SEND_MESSAGE_LIST = 'CLOUD_SEND_MESSAGE_LIST' // 智能玩法列表
export const CLOUD_SEND_MESSAGE_PAGINATION = 'CLOUD_SEND_MESSAGE_PAGINATION' // 智能玩法列表分页
export const CLOUD_SEND_MESSAGE_POST_DETAIL = 'CLOUD_SEND_MESSAGE_POST_DETAIL' // 智能玩法文章详情

// 设备折线图
export const CLOUD_HISTORY_REPORT = 'CLOUD_HISTORY_REPORT' // 智能设备折线
export const CLOUD_RUNTIME_REPORT = 'CLOUD_RUNTIME_REPORT' // 智能时间折线
export const CLOUD_NETWORK_REPORT = 'CLOUD_NETWORK_REPORT' // 配网失败率折线

export const CLOUD_DEVICE_COUNT = 'CLOUD_DEVICE_COUNT' // 设备总数
export const CLOUD_DEVICE_DETAIL_LIST = 'CLOUD_DEVICE_DETAIL_LIST' // 设备详情列表
export const CLOUD_DEVICE_DETAIL_PAGINATION = 'CLOUD_DEVICE_DETAIL_PAGINATION' // 设备详情分页

export const CLOUD_HOME_DETAIL_LIST = 'CLOUD_HOME_DETAIL_LIST' // 家庭详情分页
export const CLOUD_HOME_DETAIL_PAGINATION = 'CLOUD_HOME_DETAIL_PAGINATION' // 家庭详情分页
export const CLOUD_HOME_DETAIL_SEARCH_DICT = 'CLOUD_HOME_DETAIL_SEARCH_DICT' // 家庭详情搜索字典

export const CLOUD_NETWORK_DETAIL_LIST = 'CLOUD_NETWORK_DETAIL_LIST' // 配网成功率详情列表
export const CLOUD_NETWORK_DETAIL_PAGINATION = 'CLOUD_NETWORK_DETAIL_PAGINATION' // 配网成功率详情分页
export const CLOUD_NETWORK_MODE_TYPE_LIST = 'CLOUD_NETWORK_MODE_TYPE_LIST' // 配网成功率支持的设备列表

export const CLOUD_HOME_COMFORT_SCENE = 'CLOUD_HOME_COMFORT_SCENE' // 舒适度场景
export const CLOUD_HOME_COMFORT_SCENE_PAGINATION = 'CLOUD_HOME_COMFORT_SCENE_PAGINATION' // 舒适度场景分页页码
export const CLOUD_HOME_COMFORT_SCENE_STATISTICS = 'CLOUD_HOME_COMFORT_SCENE_STATISTICS' // 舒适度场景统计报表
export const CLOUD_ALARM_CHART = 'CLOUD_ALARM_CHART'
export const CLOUD_SEND_MESSAGE_DETAIL_CHART = 'CLOUD_SEND_MESSAGE_DETAIL_CHART' // 消息推送效果详情
export const CLOUD_USER_FEEDBACK_LIST = 'CLOUD_USER_FEEDBACK_LIST' // 用户反馈列表
export const CLOUD_USER_FEEDBACK_PAGINATION = 'CLOUD_USER_FEEDBACK_PAGINATION' // 用户反馈列表分页
export const CLOUD_COMFORT_ENCYCLOPEDIA_LIST = 'CLOUD_COMFORT_ENCYCLOPEDIA_LIST' // 舒适小百科列表
export const CLOUD_COMFORT_ENCYCLOPEDIA_LIST_PAGINATION = 'CLOUD_COMFORT_ENCYCLOPEDIA_LIST_PAGINATION' // 舒适小百科分页页码
export const CLOUD_COMFORT_ENCYCLOPEDIA_DETAIL = 'CLOUD_COMFORT_ENCYCLOPEDIA_DETAIL' // 舒适小百科详情

export const KNOWLEDGE_CATALOGUE_LIST = 'KNOWLEDGE_CATALOGUE_LIST' // 知识管理库目录
export const KNOWLEDGE_QUESTION_LIST = 'KNOWLEDGE_QUESTION_LIST' // 问题列表
export const KNOWLEDGE_QUESTION_DETAIL = 'KNOWLEDGE_QUESTION_DETAIL' // 问题详情

export const GET_OUTBOUND_LIST = 'GET_OUTBOUND_LIST' // 出仓管理列表
export const OUTBOUND_PAGINATION = 'OUTBOUND_PAGINATION' // 出仓管理列表页码
export const SPLASH_SCREEN_LIST = 'SPLASH_SCREEN_LIST' // 闪屏管理列表
export const SPLASH_SCREEN_PAGINATION = 'SPLASH_SCREEN_PAGINATION' // 闪屏管理列表页码
export const AD_POP_LIST = 'AD_POP_LIST' // 弹窗广告列表
export const AD_POP_PAGINATION = 'AD_POP_PAGINATION' // 弹窗广告列表页码
export const GET_ALL_ACTIVITY = 'GET_ALL_ACTIVITY' // 获取所有活动
export const GET_CUSTOMER_SERVICE_LIST = 'GET_CUSTOMER_SERVICE_LIST' // 获取客服列表
export const GET_CUSTOMER_SERVICE_PAGINATION = 'GET_CUSTOMER_SERVICE_PAGINATION' // 客服列表页码

export const GET_CLOUD_HOME_MODE_TYPE_LIST = 'GET_CLOUD_HOME_MODE_TYPE_LIST' // 获取模块类型列表
export const GET_SERVICE_MANAGE_HISTORY_LIST = 'GET_SERVICE_MANAGE_HISTORY_LIST' // 服务管理服务列表

export const GET_CLOUD_MERCHANT_LIST = 'GET_CLOUD_MERCHANT_LIST' // 获取招商代理商列表
export const GET_CLOUD_MERCHANT_DETAIL_LIST = 'GET_CLOUD_MERCHANT_DETAIL_LIST' // 代理商代理详情
export const GET_CLOUD_MERCHANT_DETAIL_LIST_PAGINATION = 'GET_CLOUD_MERCHANT_DETAIL_LIST_PAGINATION' // 代理商代理详情分页
export const GET_CLOUD_MERCHANT_DETAIL_STATS = 'GET_CLOUD_MERCHANT_DETAIL_STATS' // 代理商详情统计
export const GET_CLOUD_MERCHANT_CASE_LIST = 'GET_CLOUD_MERCHANT_CASE_LIST' // 获取用户方案
export const GET_CLOUD_MERCHANT_CASE_DETAIL_LIST = 'GET_CLOUD_MERCHANT_CASE_DETAIL_LIST' // 获取用户方案
export const GET_CLOUD_MERCHANT_FROM_PHONE = 'GET_CLOUD_MERCHANT_FROM_PHONE' // 获取招商代理商列表
export const CLOUD_MERCHANT_LIST_PAGINATION = 'CLOUD_MERCHANT_LIST_PAGINATION' // 招商代理列表分页
export const CLOUD_MERCHANT_AGENT_DETAIL = 'CLOUD_MERCHANT_AGENT_DETAIL' // 招商代理订单详情
export const GET_CLOUD_MERCHANT_AD_LIST = 'GET_CLOUD_MERCHANT_AD_LIST' // 获取招商广告列表
export const GET_CLOUD_MERCHANT_AD_LIST_PAGINATION = 'GET_CLOUD_MERCHANT_AD_LIST_PAGINATION' // 招商广告列表分页
export const GET_CLOUD_MERCHANT_AD_DETAIL = 'GET_CLOUD_MERCHANT_AD_DETAIL' // 获取招商广告详情
export const GET_CLOUD_MERCHANT_AGENCY_ORDER_DETAIL = 'GET_CLOUD_MERCHANT_AGENCY_ORDER_DETAIL' // 获取招商代理订单详情
export const GET_CLOUD_MERCHANT_ORDER_LIST = 'GET_CLOUD_MERCHANT_ORDER_LIST' //  获取招商订单列表
export const GET_CLOUD_MERCHANT_ORDER_DETAIL = 'GET_CLOUD_MERCHANT_ORDER_DETAIL' //  获取招商订单列表
export const GET_CLOUD_MERCHANT_ORDER_LIST_PAGINATION = 'GET_CLOUD_MERCHANT_ORDER_LIST_PAGINATION' //  招商订单列表分页

export const GET_CLOUD_MERCHANT_SHOP_LIST = 'GET_CLOUD_MERCHANT_SHOP_LIST' //  获取商品列表
export const GET_CLOUD_MERCHANT_SHOP_LIST_PAGINATION = 'GET_CLOUD_MERCHANT_SHOP_LIST_PAGINATION' //  商品列表分页
export const GET_CLOUD_MERCHANT_SHOP_CATEGORY_LIST = 'GET_CLOUD_MERCHANT_SHOP_CATEGORY_LIST' //  小程序商品品类
export const GET_CLOUD_MERCHANT_SHOP_CATEGORY_TYPE_LIST = 'GET_CLOUD_MERCHANT_SHOP_CATEGORY_TYPE_LIST' //  小程序商品类型

export const GET_CLOUD_OUTBOUND_DEVICE_LIST = 'GET_CLOUD_OUTBOUND_DEVICE_LIST' // 出库设备型号
export const GET_CLOUD_OUTBOUND_MERCHANT_LIST = 'GET_CLOUD_OUTBOUND_MERCHANT_LIST' // 出库管理匹配经销商列表
export const GET_CLOUD_OUTBOUND_CATEGORY_LIST = 'GET_CLOUD_OUTBOUND_CATEGORY_LIST' // 出库管理匹配经销商列表

export const GET_CLOUD_MERCHANT_RECOMMEND_LIST = 'GET_CLOUD_MERCHANT_RECOMMEND_LIST' // 推荐榜单
export const GET_CLOUD_MERCHANT_RECOMMEND_LIST_PAGINATION = 'GET_CLOUD_MERCHANT_RECOMMEND_LIST_PAGINATION' // 推荐榜单分页

export const GET_CLOUD_MERCHANT_CLASSIFY_LIST = 'GET_CLOUD_MERCHANT_CLASSIFY_LIST' // 主营产品分类
export const GET_CLOUD_MERCHANT_CLASSIFY_LIST_PAGINATION = 'GET_CLOUD_MERCHANT_CLASSIFY_LIST_PAGINATION' // 主营产品分类分页

export const GET_CLOUD_MERCHANT_PRODUCT_ORDER_LIST = 'GET_CLOUD_MERCHANT_PRODUCT_ORDER_LIST' // 微信订单列表
export const GET_CLOUD_MERCHANT_PRODUCT_ORDER_LIST_PAGINATION = 'GET_CLOUD_MERCHANT_PRODUCT_ORDER_LIST_PAGINATION' // 微信订单列表分页
export const GET_CLOUD_MERCHANT_PRODUCT_OUT_ORDER_LIST = 'GET_CLOUD_MERCHANT_PRODUCT_OUT_ORDER_LIST' // 外部订单列表
export const GET_CLOUD_MERCHANT_PRODUCT_OUT_ORDER_LIST_PAGINATION = 'GET_CLOUD_MERCHANT_PRODUCT_OUT_ORDER_LIST_PAGINATION' // 微信订单列表分页
export const GET_CLOUD_MERCHANT_PRODUCT_ORDER_DETAIL = 'GET_CLOUD_MERCHANT_PRODUCT_ORDER_DETAIL' // 微信订单详情
export const GET_CLOUD_MERCHANT_PRODUCT_OUT_ORDER_DETAIL = 'GET_CLOUD_MERCHANT_PRODUCT_OUT_ORDER_DETAIL' // 外部订单详情
export const GET_CLOUD_MERCHANT_PRODUCT_ORDER_TOTAL = 'GET_CLOUD_MERCHANT_PRODUCT_ORDER_TOTAL' // 微信订单统计
export const MERCHANT_MEMBERS_INVITATION_OUT_ORDER_DATA = 'MERCHANT_MEMBERS_INVITATION_OUT_ORDER_DATA' // 微信订单统计
export const MERCHANT_MEMBERS_INVITATION_PROJECT_DATA = 'MERCHANT_MEMBERS_INVITATION_PROJECT_DATA' // 外部客户工程项目
export const GET_CLOUD_MERCHANT_TAG_LIST = 'GET_CLOUD_MERCHANT_TAG_LIST' // boss标签
export const GET_CLOUD_MERCHANT_MEMBER_COMMUNICATION_LIST = 'GET_CLOUD_MERCHANT_MEMBER_COMMUNICATION_LIST' // 沟通记录列表
export const GET_CLOUD_MERCHANT_MEMBER_COMMUNICATION_LIST_PAGINATION = 'GET_CLOUD_MERCHANT_MEMBER_COMMUNICATION_LIST_PAGINATION'
export const GET_CLOUD_MERCHANT_MEMBER_DEPARTMENT_LIST = 'GET_CLOUD_MERCHANT_MEMBER_DEPARTMENT_LIST' // 获取分部列表
export const GET_CLOUD_MERCHANT_MATERIAL_LIST = 'GET_CLOUD_MERCHANT_MATERIAL_LIST' // 获取营销物料列表

export const GET_CLOUD_MERCHANT_PROJECT_SCHEME_LIST = 'GET_CLOUD_MERCHANT_PROJECT_SCHEME_LIST' // 工程方案列表
export const GET_CLOUD_MERCHANT_PROJECT_SCHEME_LIST_PAGINATION = 'GET_CLOUD_MERCHANT_PROJECT_SCHEME_LIST_PAGINATION' // 工程方案列表分页
export const GET_CLOUD_MERCHANT_PROJECT_SCHEME_DETAIL = 'GET_CLOUD_MERCHANT_PROJECT_SCHEME_DETAIL' // 工程方案详情

export const GET_CLOUD_MERCHANT_CANUNBIND_DEVICE_LIST = 'GET_CLOUD_MERCHANT_CANUNBIND_DEVICE_LIST' // boss端可解绑设备
export const GET_CLOUD_MERCHANT_BIND_RECORDS = 'GET_CLOUD_MERCHANT_BIND_RECORDS' // boss端解绑设备记录
export const GET_CLOUD_MERCHANT_COMPLAINT_ORDER_RECORDS = 'GET_CLOUD_MERCHANT_COMPLAINT_ORDER_RECORDS' // 投诉工单列表
export const GET_CLOUD_MERCHANT_COMPLAINT_ORDER_DETAIL = 'GET_CLOUD_MERCHANT_COMPLAINT_ORDER_DETAIL' // 投诉工单详情
export const GET_CLOUD_MERCHANT_COMPLAINT_PROCESS_ORDER_LIST = 'GET_CLOUD_MERCHANT_COMPLAINT_PROCESS_ORDER_LIST' // 投诉工单跟进记录列表
export const GET_CLOUD_MERCHANT_COMPLAINT_PROCESS_ORDER_DETAIL = 'GET_CLOUD_MERCHANT_COMPLAINT_PROCESS_ORDER_DETAIL' // 投诉工单跟进记录详情

export const GET_CLOUD_SERVICE_REMIND_LIST = 'GET_CLOUD_SERVICE_REMIND_LIST' // 服务机会列表
export const GET_CLOUD_SERVICE_REMIND_LIST_PAGINATION = 'GET_CLOUD_SERVICE_REMIND_LIST_PAGINATION' // 服务机会分页

export const GET_CLOUD_CONTROL_PROJECT_LIST = 'GET_CLOUD_CONTROL_PROJECT_LIST' // 集控项目列表
export const GET_CLOUD_CONTROL_PROJECT_DETAIL = 'GET_CLOUD_CONTROL_PROJECT_DETAIL' // 集控项目详情
export const GET_CLOUD_PROJECT_DEVICES_TYPES = 'GET_CLOUD_PROJECT_DEVICES_TYPES' // 获取工程端一级设备类型
