export const BUSINESS_DATA = 'BUSINESS_DATA'

export const BUSINESS_DETAIL = 'BUSINESS_DETAIL'

export const CRMSTATIC_LOAN = 'CRMSTATIC_LOAN'

export const PLAT_LIST = 'PLAT_LIST'

export const WHITE_RECORDS = 'WHITE_RECORDS'
