export const FREIGHT_RULE_DATA = 'FREIGHT_RULE_DATA'

export const FREIGHT_RULE_INFO = 'FREIGHT_RULE_INFO'

export const WAREHOUSR_PRODUCT_DATA = 'WAREHOUSR_PRODUCT_DATA'

export const WAREHOUSR_PRODUCT_INFO = 'WAREHOUSR_PRODUCT_INFO'

export const MERCHANT_DATA = 'MERCHANT_DATA'

export const SET_SELECT_WAREHOUSE_PRODUCT = 'SET_SELECT_WAREHOUSE_PRODUCT'

export const FREIGHT_PRODUCT_DATA = 'FREIGHT_PRODUCT_DATA'

// 存在spu的品牌
export const EXIST_SPU_BRAND = 'EXIST_SPU_BRAND'
// 存在spu的类目
export const EXIST_SPU_CATEGORY = 'EXIST_SPU_CATEGORY'
