// 商品库列表pageNumber
export const CHANGE_MANAGE_PAGE_NUMBER = 'CHANGE_MANAGE_PAGE_NUMBER'
// 商品审核pageNumber
export const CHANGE_REVIEW_LIST_PAGE_NUMBER = 'CHANGE_REVIEW_LIST_PAGE_NUMBER'
// 获取用户机构名字和code
export const GET_USER_INFO_NAME_AND_CODE = 'GET_USER_INFO_NAME_AND_CODE'
