export const SEARCH_WORD_DATA = 'SEARCH_WORD_DATA'
export const SEARCH_WORD_INFO = 'SEARCH_WORD_INFO'
export const VALID_SEARCH_DATA = 'VALID_SEARCH_DATA'
export const CLICK_RATE_DATA = 'CLICK_RATE_DATA'
export const NO_RESULT_DATA = 'NO_RESULT_DATA'

/* 2020-12-04 搜索词和同义词 starting */
export const CUSTOM_DICT_DATA = 'CUSTOM_DICT_DATA'
export const POST_CUSTOM_DICT = 'POST_CUSTOM_DICT'
export const PUT_CUSTOM_DICT = 'PUT_CUSTOM_DICT'
export const DELETE_CUSTOM_DICT = 'DELETE_CUSTOM_DICT'
/* 2020-12-04 搜索词和同义词 ending */
