export const BACK_MONEY_TRACK_LIST = 'BACK_MONEY_TRACK_LIST' // 回款跟踪
export const BACK_MONEY_TRACK_PAGINATION = 'BACK_MONEY_TRACK_PAGINATION'
export const BACK_MONEY_TRACK_TOTAL = 'BACK_MONEY_TRACK_TOTAL'
