export const CREDIT_DATA = 'CREDIT_DATA'

export const CREDIT_PAGE = 'CREDIT_PAGE'

export const CREDIT_DETAIL = 'CREDIT_DETAIL'

export const CREDIT_DOCUMENT = 'CREDIT_DOCUMENT'

export const CREDIT_RECORDS = 'CREDIT_RECORDS'
