export const SPIKE_PRICE_DATA = 'SPIKE_PRICE_DATA'
export const SPIKE_PRICE_INFO = 'SPIKE_PRICE_INFO'
export const SPECIAL_PRICE_DATA = 'SPECIAL_PRICE_DATA'

export const COUPON_USE_DATA = 'COUPON_USE_DATA'
// 交易额明细
export const GET_TRANSACTION_INFO = 'GET_TRANSACTION_INFO'
