export const SPIKE_PRICE_DATA = 'SPIKE_PRICE_DATA'
export const SPIKE_PRICE_INFO = 'SPIKE_PRICE_INFO'
export const SPECIAL_PRICE_DATA = 'SPECIAL_PRICE_DATA'

export const COUPON_USE_DATA = 'COUPON_USE_DATA'
// 交易额明细
export const GET_TRANSACTION_INFO = 'GET_TRANSACTION_INFO' // 交易额明细
export const GET_ORDINARY_BI_GOOD_DETAIL = 'GET_ORDINARY_BI_GOOD_DETAIL' // 商品明细-普通商品
export const GET_SPIKE_BI_GOOD_DETAIL = 'GET_SPIKE_BI_GOOD_DETAIL' // 商品明细-秒杀商品
export const INIT_BI_GOOD_DETAIL = 'INIT_BI_GOOD_DETAIL' // 清空table
